import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import AuthSessionProvider from "@/components/providers/AuthSessionProvider";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast"

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthSessionProvider>
        <body className={nunito.className}>
          <Toaster />
          <Navbar />
          {children}
        </body>
      </AuthSessionProvider>
    </html>
  );
}
